package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/hpcloud/cf-plugin-usb/lib/models"
)

// CreateServicePlanReader is a Reader for the CreateServicePlan structure.
type CreateServicePlanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *CreateServicePlanReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateServicePlanCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewCreateServicePlanInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateServicePlanCreated creates a CreateServicePlanCreated with default headers values
func NewCreateServicePlanCreated() *CreateServicePlanCreated {
	return &CreateServicePlanCreated{}
}

/*CreateServicePlanCreated handles this case with default header values.

Sucessfull response
*/
type CreateServicePlanCreated struct {
	Payload *models.Plan
}

func (o *CreateServicePlanCreated) Error() string {
	return fmt.Sprintf("[POST /plans][%d] createServicePlanCreated  %+v", 201, o.Payload)
}

func (o *CreateServicePlanCreated) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Plan)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateServicePlanInternalServerError creates a CreateServicePlanInternalServerError with default headers values
func NewCreateServicePlanInternalServerError() *CreateServicePlanInternalServerError {
	return &CreateServicePlanInternalServerError{}
}

/*CreateServicePlanInternalServerError handles this case with default header values.

Unexpected error
*/
type CreateServicePlanInternalServerError struct {
	Payload string
}

func (o *CreateServicePlanInternalServerError) Error() string {
	return fmt.Sprintf("[POST /plans][%d] createServicePlanInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateServicePlanInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
