package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hpcloud/cf-plugin-usb/lib/models"
)

// NewCreateInstanceParams creates a new CreateInstanceParams object
// with the default values initialized.
func NewCreateInstanceParams() *CreateInstanceParams {
	var ()
	return &CreateInstanceParams{}
}

/*CreateInstanceParams contains all the parameters to send to the API endpoint
for the create instance operation typically these are written to a http.Request
*/
type CreateInstanceParams struct {

	/*Instance
	  Instance to be created

	*/
	Instance *models.Instance
}

// WithInstance adds the instance to the create instance params
func (o *CreateInstanceParams) WithInstance(Instance *models.Instance) *CreateInstanceParams {
	o.Instance = Instance
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CreateInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	if o.Instance == nil {
		o.Instance = new(models.Instance)
	}

	if err := r.SetBodyParam(o.Instance); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
