package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hpcloud/cf-plugin-usb/lib/models"
)

// CreateDriverReader is a Reader for the CreateDriver structure.
type CreateDriverReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *CreateDriverReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateDriverCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewCreateDriverConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewCreateDriverInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateDriverCreated creates a CreateDriverCreated with default headers values
func NewCreateDriverCreated() *CreateDriverCreated {
	return &CreateDriverCreated{}
}

/*CreateDriverCreated handles this case with default header values.

Driver created
*/
type CreateDriverCreated struct {
	Payload *models.Driver
}

func (o *CreateDriverCreated) Error() string {
	return fmt.Sprintf("[POST /drivers][%d] createDriverCreated  %+v", 201, o.Payload)
}

func (o *CreateDriverCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Driver)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDriverConflict creates a CreateDriverConflict with default headers values
func NewCreateDriverConflict() *CreateDriverConflict {
	return &CreateDriverConflict{}
}

/*CreateDriverConflict handles this case with default header values.

A driver with the same type already exists
*/
type CreateDriverConflict struct {
}

func (o *CreateDriverConflict) Error() string {
	return fmt.Sprintf("[POST /drivers][%d] createDriverConflict ", 409)
}

func (o *CreateDriverConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateDriverInternalServerError creates a CreateDriverInternalServerError with default headers values
func NewCreateDriverInternalServerError() *CreateDriverInternalServerError {
	return &CreateDriverInternalServerError{}
}

/*CreateDriverInternalServerError handles this case with default header values.

Unexpected error
*/
type CreateDriverInternalServerError struct {
	Payload string
}

func (o *CreateDriverInternalServerError) Error() string {
	return fmt.Sprintf("[POST /drivers][%d] createDriverInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateDriverInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
