package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/hpcloud/cf-plugin-usb/lib/models"
)

// NewCreateServicePlanParams creates a new CreateServicePlanParams object
// with the default values initialized.
func NewCreateServicePlanParams() *CreateServicePlanParams {
	var ()
	return &CreateServicePlanParams{}
}

/*CreateServicePlanParams contains all the parameters to send to the API endpoint
for the create service plan operation typically these are written to a http.Request
*/
type CreateServicePlanParams struct {

	/*Plan
	  Add a plan for a **dialID**

	*/
	Plan *models.Plan
}

// WithPlan adds the plan to the create service plan params
func (o *CreateServicePlanParams) WithPlan(plan *models.Plan) *CreateServicePlanParams {
	o.Plan = plan
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CreateServicePlanParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Plan == nil {
		o.Plan = new(models.Plan)
	}

	if err := r.SetBodyParam(o.Plan); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
