package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hpcloud/cf-plugin-usb/lib/models"
)

// CreateDriverInstanceReader is a Reader for the CreateDriverInstance structure.
type CreateDriverInstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *CreateDriverInstanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateDriverInstanceCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewCreateDriverInstanceConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewCreateDriverInstanceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateDriverInstanceCreated creates a CreateDriverInstanceCreated with default headers values
func NewCreateDriverInstanceCreated() *CreateDriverInstanceCreated {
	return &CreateDriverInstanceCreated{}
}

/*CreateDriverInstanceCreated handles this case with default header values.

Instance created
*/
type CreateDriverInstanceCreated struct {
	Payload *models.DriverInstance
}

func (o *CreateDriverInstanceCreated) Error() string {
	return fmt.Sprintf("[POST /driver_instances][%d] createDriverInstanceCreated  %+v", 201, o.Payload)
}

func (o *CreateDriverInstanceCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DriverInstance)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDriverInstanceConflict creates a CreateDriverInstanceConflict with default headers values
func NewCreateDriverInstanceConflict() *CreateDriverInstanceConflict {
	return &CreateDriverInstanceConflict{}
}

/*CreateDriverInstanceConflict handles this case with default header values.

Conflict
*/
type CreateDriverInstanceConflict struct {
}

func (o *CreateDriverInstanceConflict) Error() string {
	return fmt.Sprintf("[POST /driver_instances][%d] createDriverInstanceConflict ", 409)
}

func (o *CreateDriverInstanceConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateDriverInstanceInternalServerError creates a CreateDriverInstanceInternalServerError with default headers values
func NewCreateDriverInstanceInternalServerError() *CreateDriverInstanceInternalServerError {
	return &CreateDriverInstanceInternalServerError{}
}

/*CreateDriverInstanceInternalServerError handles this case with default header values.

Unexpected error
*/
type CreateDriverInstanceInternalServerError struct {
	Payload string
}

func (o *CreateDriverInstanceInternalServerError) Error() string {
	return fmt.Sprintf("[POST /driver_instances][%d] createDriverInstanceInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateDriverInstanceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
