package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hpcloud/cf-plugin-usb/lib/models"
)

// CreateDialReader is a Reader for the CreateDial structure.
type CreateDialReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *CreateDialReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateDialCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewCreateDialInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateDialCreated creates a CreateDialCreated with default headers values
func NewCreateDialCreated() *CreateDialCreated {
	return &CreateDialCreated{}
}

/*CreateDialCreated handles this case with default header values.

Sucessfull response
*/
type CreateDialCreated struct {
	Payload *models.Dial
}

func (o *CreateDialCreated) Error() string {
	return fmt.Sprintf("[POST /dials][%d] createDialCreated  %+v", 201, o.Payload)
}

func (o *CreateDialCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Dial)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDialInternalServerError creates a CreateDialInternalServerError with default headers values
func NewCreateDialInternalServerError() *CreateDialInternalServerError {
	return &CreateDialInternalServerError{}
}

/*CreateDialInternalServerError handles this case with default header values.

Unexpected error
*/
type CreateDialInternalServerError struct {
	Payload string
}

func (o *CreateDialInternalServerError) Error() string {
	return fmt.Sprintf("[POST /dials][%d] createDialInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateDialInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
