package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteDriverInstanceReader is a Reader for the DeleteDriverInstance structure.
type DeleteDriverInstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteDriverInstanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteDriverInstanceNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDeleteDriverInstanceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteDriverInstanceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteDriverInstanceNoContent creates a DeleteDriverInstanceNoContent with default headers values
func NewDeleteDriverInstanceNoContent() *DeleteDriverInstanceNoContent {
	return &DeleteDriverInstanceNoContent{}
}

/*DeleteDriverInstanceNoContent handles this case with default header values.

Driver deleted
*/
type DeleteDriverInstanceNoContent struct {
}

func (o *DeleteDriverInstanceNoContent) Error() string {
	return fmt.Sprintf("[DELETE /driver_instances/{driver_instance_id}][%d] deleteDriverInstanceNoContent ", 204)
}

func (o *DeleteDriverInstanceNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDriverInstanceNotFound creates a DeleteDriverInstanceNotFound with default headers values
func NewDeleteDriverInstanceNotFound() *DeleteDriverInstanceNotFound {
	return &DeleteDriverInstanceNotFound{}
}

/*DeleteDriverInstanceNotFound handles this case with default header values.

Not Found
*/
type DeleteDriverInstanceNotFound struct {
}

func (o *DeleteDriverInstanceNotFound) Error() string {
	return fmt.Sprintf("[DELETE /driver_instances/{driver_instance_id}][%d] deleteDriverInstanceNotFound ", 404)
}

func (o *DeleteDriverInstanceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDriverInstanceInternalServerError creates a DeleteDriverInstanceInternalServerError with default headers values
func NewDeleteDriverInstanceInternalServerError() *DeleteDriverInstanceInternalServerError {
	return &DeleteDriverInstanceInternalServerError{}
}

/*DeleteDriverInstanceInternalServerError handles this case with default header values.

Unexpected error
*/
type DeleteDriverInstanceInternalServerError struct {
	Payload string
}

func (o *DeleteDriverInstanceInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /driver_instances/{driver_instance_id}][%d] deleteDriverInstanceInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteDriverInstanceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
