package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"
)

type DeleteDriverInstanceReader struct {
	formats strfmt.Registry
}

func (o *DeleteDriverInstanceReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteDriverInstanceNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDeleteDriverInstanceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteDriverInstanceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteDriverInstanceNoContent creates a DeleteDriverInstanceNoContent with default headers values
func NewDeleteDriverInstanceNoContent() *DeleteDriverInstanceNoContent {
	return &DeleteDriverInstanceNoContent{}
}

/*DeleteDriverInstanceNoContent

Driver deleted
*/
type DeleteDriverInstanceNoContent struct {
}

func (o *DeleteDriverInstanceNoContent) Error() string {
	return fmt.Sprintf("[DELETE /driver_instances/{driver_instance_id}][%d] deleteDriverInstanceNoContent ", 204)
}

func (o *DeleteDriverInstanceNoContent) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDriverInstanceNotFound creates a DeleteDriverInstanceNotFound with default headers values
func NewDeleteDriverInstanceNotFound() *DeleteDriverInstanceNotFound {
	return &DeleteDriverInstanceNotFound{}
}

/*DeleteDriverInstanceNotFound

Not Found
*/
type DeleteDriverInstanceNotFound struct {
}

func (o *DeleteDriverInstanceNotFound) Error() string {
	return fmt.Sprintf("[DELETE /driver_instances/{driver_instance_id}][%d] deleteDriverInstanceNotFound ", 404)
}

func (o *DeleteDriverInstanceNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDriverInstanceInternalServerError creates a DeleteDriverInstanceInternalServerError with default headers values
func NewDeleteDriverInstanceInternalServerError() *DeleteDriverInstanceInternalServerError {
	return &DeleteDriverInstanceInternalServerError{}
}

/*DeleteDriverInstanceInternalServerError

Unexpected error
*/
type DeleteDriverInstanceInternalServerError struct {
	Payload string
}

func (o *DeleteDriverInstanceInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /driver_instances/{driver_instance_id}][%d] deleteDriverInstanceInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteDriverInstanceInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
