package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewDeleteDriverInstanceParams creates a new DeleteDriverInstanceParams object
// with the default values initialized.
func NewDeleteDriverInstanceParams() *DeleteDriverInstanceParams {
	var ()
	return &DeleteDriverInstanceParams{}
}

/*DeleteDriverInstanceParams contains all the parameters to send to the API endpoint
for the delete driver instance operation typically these are written to a http.Request
*/
type DeleteDriverInstanceParams struct {

	/*DriverInstanceID
	  Driver Instance ID

	*/
	DriverInstanceID string
}

// WithDriverInstanceID adds the driverInstanceId to the delete driver instance params
func (o *DeleteDriverInstanceParams) WithDriverInstanceID(driverInstanceId string) *DeleteDriverInstanceParams {
	o.DriverInstanceID = driverInstanceId
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDriverInstanceParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param driver_instance_id
	if err := r.SetPathParam("driver_instance_id", o.DriverInstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
