package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"
)

// DeleteDialReader is a Reader for the DeleteDial structure.
type DeleteDialReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteDialReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteDialNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDeleteDialNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteDialInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteDialNoContent creates a DeleteDialNoContent with default headers values
func NewDeleteDialNoContent() *DeleteDialNoContent {
	return &DeleteDialNoContent{}
}

/*DeleteDialNoContent handles this case with default header values.

Sucessfull response
*/
type DeleteDialNoContent struct {
}

func (o *DeleteDialNoContent) Error() string {
	return fmt.Sprintf("[DELETE /dials/{dial_id}][%d] deleteDialNoContent ", 204)
}

func (o *DeleteDialNoContent) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDialNotFound creates a DeleteDialNotFound with default headers values
func NewDeleteDialNotFound() *DeleteDialNotFound {
	return &DeleteDialNotFound{}
}

/*DeleteDialNotFound handles this case with default header values.

Not Found
*/
type DeleteDialNotFound struct {
}

func (o *DeleteDialNotFound) Error() string {
	return fmt.Sprintf("[DELETE /dials/{dial_id}][%d] deleteDialNotFound ", 404)
}

func (o *DeleteDialNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDialInternalServerError creates a DeleteDialInternalServerError with default headers values
func NewDeleteDialInternalServerError() *DeleteDialInternalServerError {
	return &DeleteDialInternalServerError{}
}

/*DeleteDialInternalServerError handles this case with default header values.

Unexpected error
*/
type DeleteDialInternalServerError struct {
	Payload string
}

func (o *DeleteDialInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /dials/{dial_id}][%d] deleteDialInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteDialInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
