package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"
)

// DeleteServicePlanReader is a Reader for the DeleteServicePlan structure.
type DeleteServicePlanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteServicePlanReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteServicePlanNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDeleteServicePlanNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteServicePlanInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteServicePlanNoContent creates a DeleteServicePlanNoContent with default headers values
func NewDeleteServicePlanNoContent() *DeleteServicePlanNoContent {
	return &DeleteServicePlanNoContent{}
}

/*DeleteServicePlanNoContent handles this case with default header values.

Sucessfull response
*/
type DeleteServicePlanNoContent struct {
}

func (o *DeleteServicePlanNoContent) Error() string {
	return fmt.Sprintf("[DELETE /plans/{plan_id}][%d] deleteServicePlanNoContent ", 204)
}

func (o *DeleteServicePlanNoContent) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteServicePlanNotFound creates a DeleteServicePlanNotFound with default headers values
func NewDeleteServicePlanNotFound() *DeleteServicePlanNotFound {
	return &DeleteServicePlanNotFound{}
}

/*DeleteServicePlanNotFound handles this case with default header values.

Not Found
*/
type DeleteServicePlanNotFound struct {
}

func (o *DeleteServicePlanNotFound) Error() string {
	return fmt.Sprintf("[DELETE /plans/{plan_id}][%d] deleteServicePlanNotFound ", 404)
}

func (o *DeleteServicePlanNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteServicePlanInternalServerError creates a DeleteServicePlanInternalServerError with default headers values
func NewDeleteServicePlanInternalServerError() *DeleteServicePlanInternalServerError {
	return &DeleteServicePlanInternalServerError{}
}

/*DeleteServicePlanInternalServerError handles this case with default header values.

Unexpected error
*/
type DeleteServicePlanInternalServerError struct {
	Payload string
}

func (o *DeleteServicePlanInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /plans/{plan_id}][%d] deleteServicePlanInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteServicePlanInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
