package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteInstanceParams creates a new DeleteInstanceParams object
// with the default values initialized.
func NewDeleteInstanceParams() *DeleteInstanceParams {
	var ()
	return &DeleteInstanceParams{}
}

/*DeleteInstanceParams contains all the parameters to send to the API endpoint
for the delete instance operation typically these are written to a http.Request
*/
type DeleteInstanceParams struct {

	/*InstanceID
	  Instance ID

	*/
	InstanceID string
}

// WithInstanceID adds the instanceId to the delete instance params
func (o *DeleteInstanceParams) WithInstanceID(InstanceID string) *DeleteInstanceParams {
	o.InstanceID = InstanceID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param instance_id
	if err := r.SetPathParam("instance_id", o.InstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
