package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewDeleteServicePlanParams creates a new DeleteServicePlanParams object
// with the default values initialized.
func NewDeleteServicePlanParams() *DeleteServicePlanParams {
	var ()
	return &DeleteServicePlanParams{}
}

/*DeleteServicePlanParams contains all the parameters to send to the API endpoint
for the delete service plan operation typically these are written to a http.Request
*/
type DeleteServicePlanParams struct {

	/*PlanID
	  ID of the plan

	*/
	PlanID string
}

// WithPlanID adds the planId to the delete service plan params
func (o *DeleteServicePlanParams) WithPlanID(planId string) *DeleteServicePlanParams {
	o.PlanID = planId
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteServicePlanParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param plan_id
	if err := r.SetPathParam("plan_id", o.PlanID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
