package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDriverInstancesParams creates a new GetDriverInstancesParams object
// with the default values initialized.
func NewGetDriverInstancesParams() *GetDriverInstancesParams {
	var ()
	return &GetDriverInstancesParams{}
}

/*GetDriverInstancesParams contains all the parameters to send to the API endpoint
for the get driver instances operation typically these are written to a http.Request
*/
type GetDriverInstancesParams struct {

	/*DriverID
	  Driver ID

	*/
	DriverID string
}

// WithDriverID adds the driverId to the get driver instances params
func (o *GetDriverInstancesParams) WithDriverID(DriverID string) *GetDriverInstancesParams {
	o.DriverID = DriverID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetDriverInstancesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// query param driver_id
	qrDriverID := o.DriverID
	qDriverID := qrDriverID
	if qDriverID != "" {
		if err := r.SetQueryParam("driver_id", qDriverID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
