package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewGetDriverSchemaParams creates a new GetDriverSchemaParams object
// with the default values initialized.
func NewGetDriverSchemaParams() *GetDriverSchemaParams {
	var ()
	return &GetDriverSchemaParams{}
}

/*GetDriverSchemaParams contains all the parameters to send to the API endpoint
for the get driver schema operation typically these are written to a http.Request
*/
type GetDriverSchemaParams struct {

	/*DriverID
	  Driver ID

	*/
	DriverID string
}

// WithDriverID adds the driverId to the get driver schema params
func (o *GetDriverSchemaParams) WithDriverID(driverId string) *GetDriverSchemaParams {
	o.DriverID = driverId
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetDriverSchemaParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param driver_id
	if err := r.SetPathParam("driver_id", o.DriverID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
