package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/hpcloud/cf-plugin-usb/lib/models"
)

type GetDialSchemaReader struct {
	formats strfmt.Registry
}

func (o *GetDialSchemaReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDialSchemaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetDialSchemaNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetDialSchemaInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDialSchemaOK creates a GetDialSchemaOK with default headers values
func NewGetDialSchemaOK() *GetDialSchemaOK {
	return &GetDialSchemaOK{}
}

/*GetDialSchemaOK

OK
*/
type GetDialSchemaOK struct {
	Payload models.DialSchema
}

func (o *GetDialSchemaOK) Error() string {
	return fmt.Sprintf("[GET /drivers/{driver_id}/dial_schema][%d] getDialSchemaOK  %+v", 200, o.Payload)
}

func (o *GetDialSchemaOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDialSchemaNotFound creates a GetDialSchemaNotFound with default headers values
func NewGetDialSchemaNotFound() *GetDialSchemaNotFound {
	return &GetDialSchemaNotFound{}
}

/*GetDialSchemaNotFound

Not Found
*/
type GetDialSchemaNotFound struct {
}

func (o *GetDialSchemaNotFound) Error() string {
	return fmt.Sprintf("[GET /drivers/{driver_id}/dial_schema][%d] getDialSchemaNotFound ", 404)
}

func (o *GetDialSchemaNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDialSchemaInternalServerError creates a GetDialSchemaInternalServerError with default headers values
func NewGetDialSchemaInternalServerError() *GetDialSchemaInternalServerError {
	return &GetDialSchemaInternalServerError{}
}

/*GetDialSchemaInternalServerError

Unexpected error
*/
type GetDialSchemaInternalServerError struct {
	Payload string
}

func (o *GetDialSchemaInternalServerError) Error() string {
	return fmt.Sprintf("[GET /drivers/{driver_id}/dial_schema][%d] getDialSchemaInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDialSchemaInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
