package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewGetServiceParams creates a new GetServiceParams object
// with the default values initialized.
func NewGetServiceParams() *GetServiceParams {
	var ()
	return &GetServiceParams{}
}

/*GetServiceParams contains all the parameters to send to the API endpoint
for the get service operation typically these are written to a http.Request
*/
type GetServiceParams struct {

	/*ServiceID
	  ID of the service

	*/
	ServiceID string
}

// WithServiceID adds the serviceId to the get service params
func (o *GetServiceParams) WithServiceID(serviceId string) *GetServiceParams {
	o.ServiceID = serviceId
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetServiceParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param service_id
	if err := r.SetPathParam("service_id", o.ServiceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
