package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetInstanceParams creates a new GetInstanceParams object
// with the default values initialized.
func NewGetInstanceParams() *GetInstanceParams {
	var ()
	return &GetInstanceParams{}
}

/*GetInstanceParams contains all the parameters to send to the API endpoint
for the get instance operation typically these are written to a http.Request
*/
type GetInstanceParams struct {

	/*InstanceID
	  Instance ID

	*/
	InstanceID string
}

// WithInstanceID adds the instanceId to the get instance params
func (o *GetInstanceParams) WithInstanceID(InstanceID string) *GetInstanceParams {
	o.InstanceID = InstanceID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param instance_id
	if err := r.SetPathParam("instance_id", o.InstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
