package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewGetAllDialsParams creates a new GetAllDialsParams object
// with the default values initialized.
func NewGetAllDialsParams() *GetAllDialsParams {
	var ()
	return &GetAllDialsParams{}
}

/*GetAllDialsParams contains all the parameters to send to the API endpoint
for the get all dials operation typically these are written to a http.Request
*/
type GetAllDialsParams struct {

	/*DriverInstanceID
	  Driver instance ID

	*/
	DriverInstanceID *string
}

// WithDriverInstanceID adds the driverInstanceId to the get all dials params
func (o *GetAllDialsParams) WithDriverInstanceID(driverInstanceId *string) *GetAllDialsParams {
	o.DriverInstanceID = driverInstanceId
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllDialsParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.DriverInstanceID != nil {

		// query param driver_instance_id
		var qrDriverInstanceID string
		if o.DriverInstanceID != nil {
			qrDriverInstanceID = *o.DriverInstanceID
		}
		qDriverInstanceID := qrDriverInstanceID
		if qDriverInstanceID != "" {
			if err := r.SetQueryParam("driver_instance_id", qDriverInstanceID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
