package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllDialsParams creates a new GetAllDialsParams object
// with the default values initialized.
func NewGetAllDialsParams() *GetAllDialsParams {
	var ()
	return &GetAllDialsParams{}
}

/*GetAllDialsParams contains all the parameters to send to the API endpoint
for the get all dials operation typically these are written to a http.Request
*/
type GetAllDialsParams struct {

	/*InstanceID
	  Instance ID

	*/
	InstanceID *string
}

// WithInstanceID adds the instanceId to the get all dials params
func (o *GetAllDialsParams) WithInstanceID(InstanceID *string) *GetAllDialsParams {
	o.InstanceID = InstanceID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllDialsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	if o.InstanceID != nil {

		// query param instance_id
		var qrInstanceID string
		if o.InstanceID != nil {
			qrInstanceID = *o.InstanceID
		}
		qInstanceID := qrInstanceID
		if qInstanceID != "" {
			if err := r.SetQueryParam("instance_id", qInstanceID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
