package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewGetDialSchemaParams creates a new GetDialSchemaParams object
// with the default values initialized.
func NewGetDialSchemaParams() *GetDialSchemaParams {
	var ()
	return &GetDialSchemaParams{}
}

/*GetDialSchemaParams contains all the parameters to send to the API endpoint
for the get dial schema operation typically these are written to a http.Request
*/
type GetDialSchemaParams struct {

	/*DriverID
	  Driver ID

	*/
	DriverID string
}

// WithDriverID adds the driverId to the get dial schema params
func (o *GetDialSchemaParams) WithDriverID(driverId string) *GetDialSchemaParams {
	o.DriverID = driverId
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetDialSchemaParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param driver_id
	if err := r.SetPathParam("driver_id", o.DriverID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
