package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetServicePlansParams creates a new GetServicePlansParams object
// with the default values initialized.
func NewGetServicePlansParams() *GetServicePlansParams {
	var ()
	return &GetServicePlansParams{}
}

/*GetServicePlansParams contains all the parameters to send to the API endpoint
for the get service plans operation typically these are written to a http.Request
*/
type GetServicePlansParams struct {

	/*DriverInstanceID
	  Driver Instance ID

	*/
	DriverInstanceID *string
}

// WithDriverInstanceID adds the driverInstanceId to the get service plans params
func (o *GetServicePlansParams) WithDriverInstanceID(DriverInstanceID *string) *GetServicePlansParams {
	o.DriverInstanceID = DriverInstanceID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetServicePlansParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	if o.DriverInstanceID != nil {

		// query param driver_instance_id
		var qrDriverInstanceID string
		if o.DriverInstanceID != nil {
			qrDriverInstanceID = *o.DriverInstanceID
		}
		qDriverInstanceID := qrDriverInstanceID
		if qDriverInstanceID != "" {
			if err := r.SetQueryParam("driver_instance_id", qDriverInstanceID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
