package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewGetServiceByInstanceIDParams creates a new GetServiceByInstanceIDParams object
// with the default values initialized.
func NewGetServiceByInstanceIDParams() *GetServiceByInstanceIDParams {
	var ()
	return &GetServiceByInstanceIDParams{}
}

/*GetServiceByInstanceIDParams contains all the parameters to send to the API endpoint
for the get service by instance id operation typically these are written to a http.Request
*/
type GetServiceByInstanceIDParams struct {

	/*DriverInstanceID
	  Driver instance ID

	*/
	DriverInstanceID string
}

// WithDriverInstanceID adds the driverInstanceId to the get service by instance id params
func (o *GetServiceByInstanceIDParams) WithDriverInstanceID(driverInstanceId string) *GetServiceByInstanceIDParams {
	o.DriverInstanceID = driverInstanceId
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetServiceByInstanceIDParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// query param driver_instance_id
	qrDriverInstanceID := o.DriverInstanceID
	qDriverInstanceID := qrDriverInstanceID
	if qDriverInstanceID != "" {
		if err := r.SetQueryParam("driver_instance_id", qDriverInstanceID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
