package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/hpcloud/cf-plugin-usb/lib/models"
)

// GetServicePlanReader is a Reader for the GetServicePlan structure.
type GetServicePlanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetServicePlanReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetServicePlanOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetServicePlanNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetServicePlanInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetServicePlanOK creates a GetServicePlanOK with default headers values
func NewGetServicePlanOK() *GetServicePlanOK {
	return &GetServicePlanOK{}
}

/*GetServicePlanOK handles this case with default header values.

Sucessfull response
*/
type GetServicePlanOK struct {
	Payload *models.Plan
}

func (o *GetServicePlanOK) Error() string {
	return fmt.Sprintf("[GET /plans/{plan_id}][%d] getServicePlanOK  %+v", 200, o.Payload)
}

func (o *GetServicePlanOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Plan)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetServicePlanNotFound creates a GetServicePlanNotFound with default headers values
func NewGetServicePlanNotFound() *GetServicePlanNotFound {
	return &GetServicePlanNotFound{}
}

/*GetServicePlanNotFound handles this case with default header values.

Not Found
*/
type GetServicePlanNotFound struct {
}

func (o *GetServicePlanNotFound) Error() string {
	return fmt.Sprintf("[GET /plans/{plan_id}][%d] getServicePlanNotFound ", 404)
}

func (o *GetServicePlanNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetServicePlanInternalServerError creates a GetServicePlanInternalServerError with default headers values
func NewGetServicePlanInternalServerError() *GetServicePlanInternalServerError {
	return &GetServicePlanInternalServerError{}
}

/*GetServicePlanInternalServerError handles this case with default header values.

Unexpected error
*/
type GetServicePlanInternalServerError struct {
	Payload string
}

func (o *GetServicePlanInternalServerError) Error() string {
	return fmt.Sprintf("[GET /plans/{plan_id}][%d] getServicePlanInternalServerError  %+v", 500, o.Payload)
}

func (o *GetServicePlanInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
