package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDriverInstanceParams creates a new GetDriverInstanceParams object
// with the default values initialized.
func NewGetDriverInstanceParams() *GetDriverInstanceParams {
	var ()
	return &GetDriverInstanceParams{}
}

/*GetDriverInstanceParams contains all the parameters to send to the API endpoint
for the get driver instance operation typically these are written to a http.Request
*/
type GetDriverInstanceParams struct {

	/*DriverInstanceID
	  Driver Instance ID

	*/
	DriverInstanceID string
}

// WithDriverInstanceID adds the driverInstanceId to the get driver instance params
func (o *GetDriverInstanceParams) WithDriverInstanceID(DriverInstanceID string) *GetDriverInstanceParams {
	o.DriverInstanceID = DriverInstanceID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetDriverInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param driver_instance_id
	if err := r.SetPathParam("driver_instance_id", o.DriverInstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
