package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/hpcloud/cf-plugin-usb/lib/models"
)

type GetDriverInstancesReader struct {
	formats strfmt.Registry
}

func (o *GetDriverInstancesReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDriverInstancesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetDriverInstancesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDriverInstancesOK creates a GetDriverInstancesOK with default headers values
func NewGetDriverInstancesOK() *GetDriverInstancesOK {
	return &GetDriverInstancesOK{}
}

/*GetDriverInstancesOK

OK
*/
type GetDriverInstancesOK struct {
	Payload []*models.DriverInstance
}

func (o *GetDriverInstancesOK) Error() string {
	return fmt.Sprintf("[GET /driver_instances][%d] getDriverInstancesOK  %+v", 200, o.Payload)
}

func (o *GetDriverInstancesOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDriverInstancesInternalServerError creates a GetDriverInstancesInternalServerError with default headers values
func NewGetDriverInstancesInternalServerError() *GetDriverInstancesInternalServerError {
	return &GetDriverInstancesInternalServerError{}
}

/*GetDriverInstancesInternalServerError

Unexpected error
*/
type GetDriverInstancesInternalServerError struct {
	Payload string
}

func (o *GetDriverInstancesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /driver_instances][%d] getDriverInstancesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDriverInstancesInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
