package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/hpcloud/cf-plugin-usb/lib/models"
)

type GetDriversReader struct {
	formats strfmt.Registry
}

func (o *GetDriversReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDriversOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetDriversInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDriversOK creates a GetDriversOK with default headers values
func NewGetDriversOK() *GetDriversOK {
	return &GetDriversOK{}
}

/*GetDriversOK

Successful response
*/
type GetDriversOK struct {
	Payload []*models.Driver
}

func (o *GetDriversOK) Error() string {
	return fmt.Sprintf("[GET /drivers][%d] getDriversOK  %+v", 200, o.Payload)
}

func (o *GetDriversOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDriversInternalServerError creates a GetDriversInternalServerError with default headers values
func NewGetDriversInternalServerError() *GetDriversInternalServerError {
	return &GetDriversInternalServerError{}
}

/*GetDriversInternalServerError

Unexpected error
*/
type GetDriversInternalServerError struct {
	Payload string
}

func (o *GetDriversInternalServerError) Error() string {
	return fmt.Sprintf("[GET /drivers][%d] getDriversInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDriversInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
