package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hpcloud/cf-plugin-usb/lib/models"
)

// GetAllDialsReader is a Reader for the GetAllDials structure.
type GetAllDialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetAllDialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllDialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetAllDialsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAllDialsOK creates a GetAllDialsOK with default headers values
func NewGetAllDialsOK() *GetAllDialsOK {
	return &GetAllDialsOK{}
}

/*GetAllDialsOK handles this case with default header values.

Sucessfull response
*/
type GetAllDialsOK struct {
	Payload []*models.Dial
}

func (o *GetAllDialsOK) Error() string {
	return fmt.Sprintf("[GET /dials][%d] getAllDialsOK  %+v", 200, o.Payload)
}

func (o *GetAllDialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllDialsInternalServerError creates a GetAllDialsInternalServerError with default headers values
func NewGetAllDialsInternalServerError() *GetAllDialsInternalServerError {
	return &GetAllDialsInternalServerError{}
}

/*GetAllDialsInternalServerError handles this case with default header values.

Unexpected error
*/
type GetAllDialsInternalServerError struct {
	Payload string
}

func (o *GetAllDialsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /dials][%d] getAllDialsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAllDialsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
