package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetServiceByInstanceIDParams creates a new GetServiceByInstanceIDParams object
// with the default values initialized.
func NewGetServiceByInstanceIDParams() *GetServiceByInstanceIDParams {
	var ()
	return &GetServiceByInstanceIDParams{}
}

/*GetServiceByInstanceIDParams contains all the parameters to send to the API endpoint
for the get service by instance Id operation typically these are written to a http.Request
*/
type GetServiceByInstanceIDParams struct {

	/*InstanceID
	  Instance ID

	*/
	InstanceID string
}

// WithInstanceID adds the instanceId to the get service by instance Id params
func (o *GetServiceByInstanceIDParams) WithInstanceID(InstanceID string) *GetServiceByInstanceIDParams {
	o.InstanceID = InstanceID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetServiceByInstanceIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// query param instance_id
	qrInstanceID := o.InstanceID
	qInstanceID := qrInstanceID
	if qInstanceID != "" {
		if err := r.SetQueryParam("instance_id", qInstanceID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
