package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/hpcloud/cf-plugin-usb/lib/models"
)

type GetDriverReader struct {
	formats strfmt.Registry
}

func (o *GetDriverReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDriverOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetDriverNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetDriverInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDriverOK creates a GetDriverOK with default headers values
func NewGetDriverOK() *GetDriverOK {
	return &GetDriverOK{}
}

/*GetDriverOK

OK
*/
type GetDriverOK struct {
	Payload *models.Driver
}

func (o *GetDriverOK) Error() string {
	return fmt.Sprintf("[GET /drivers/{driver_id}][%d] getDriverOK  %+v", 200, o.Payload)
}

func (o *GetDriverOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Driver)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDriverNotFound creates a GetDriverNotFound with default headers values
func NewGetDriverNotFound() *GetDriverNotFound {
	return &GetDriverNotFound{}
}

/*GetDriverNotFound

Not Found
*/
type GetDriverNotFound struct {
}

func (o *GetDriverNotFound) Error() string {
	return fmt.Sprintf("[GET /drivers/{driver_id}][%d] getDriverNotFound ", 404)
}

func (o *GetDriverNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDriverInternalServerError creates a GetDriverInternalServerError with default headers values
func NewGetDriverInternalServerError() *GetDriverInternalServerError {
	return &GetDriverInternalServerError{}
}

/*GetDriverInternalServerError

Unexpected error
*/
type GetDriverInternalServerError struct {
	Payload string
}

func (o *GetDriverInternalServerError) Error() string {
	return fmt.Sprintf("[GET /drivers/{driver_id}][%d] getDriverInternalServerError  %+v", 500, o.Payload)
}

func (o *GetDriverInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
