package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hpcloud/cf-plugin-usb/lib/models"
)

// GetInstancesReader is a Reader for the GetInstances structure.
type GetInstancesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetInstancesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetInstancesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetInstancesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetInstancesOK creates a GetInstancesOK with default headers values
func NewGetInstancesOK() *GetInstancesOK {
	return &GetInstancesOK{}
}

/*GetInstancesOK handles this case with default header values.

OK
*/
type GetInstancesOK struct {
	Payload []*models.Instance
}

func (o *GetInstancesOK) Error() string {
	return fmt.Sprintf("[GET /instances][%d] getInstancesOK  %+v", 200, o.Payload)
}

func (o *GetInstancesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInstancesInternalServerError creates a GetInstancesInternalServerError with default headers values
func NewGetInstancesInternalServerError() *GetInstancesInternalServerError {
	return &GetInstancesInternalServerError{}
}

/*GetInstancesInternalServerError handles this case with default header values.

Unexpected error
*/
type GetInstancesInternalServerError struct {
	Payload string
}

func (o *GetInstancesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /instances][%d] getInstancesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetInstancesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
