package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewGetInfoParams creates a new GetInfoParams object
// with the default values initialized.
func NewGetInfoParams() *GetInfoParams {

	return &GetInfoParams{}
}

/*GetInfoParams contains all the parameters to send to the API endpoint
for the get info operation typically these are written to a http.Request
*/
type GetInfoParams struct {
}

// WriteToRequest writes these params to a swagger request
func (o *GetInfoParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
