package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"
)

// PingDriverInstanceReader is a Reader for the PingDriverInstance structure.
type PingDriverInstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PingDriverInstanceReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPingDriverInstanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewPingDriverInstanceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPingDriverInstanceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewPingDriverInstanceOK creates a PingDriverInstanceOK with default headers values
func NewPingDriverInstanceOK() *PingDriverInstanceOK {
	return &PingDriverInstanceOK{}
}

/*PingDriverInstanceOK handles this case with default header values.

OK
*/
type PingDriverInstanceOK struct {
}

func (o *PingDriverInstanceOK) Error() string {
	return fmt.Sprintf("[GET /driver_instances/{driver_instance_id}/ping][%d] pingDriverInstanceOK ", 200)
}

func (o *PingDriverInstanceOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPingDriverInstanceNotFound creates a PingDriverInstanceNotFound with default headers values
func NewPingDriverInstanceNotFound() *PingDriverInstanceNotFound {
	return &PingDriverInstanceNotFound{}
}

/*PingDriverInstanceNotFound handles this case with default header values.

Not Found
*/
type PingDriverInstanceNotFound struct {
}

func (o *PingDriverInstanceNotFound) Error() string {
	return fmt.Sprintf("[GET /driver_instances/{driver_instance_id}/ping][%d] pingDriverInstanceNotFound ", 404)
}

func (o *PingDriverInstanceNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPingDriverInstanceInternalServerError creates a PingDriverInstanceInternalServerError with default headers values
func NewPingDriverInstanceInternalServerError() *PingDriverInstanceInternalServerError {
	return &PingDriverInstanceInternalServerError{}
}

/*PingDriverInstanceInternalServerError handles this case with default header values.

Unexpected error
*/
type PingDriverInstanceInternalServerError struct {
	Payload string
}

func (o *PingDriverInstanceInternalServerError) Error() string {
	return fmt.Sprintf("[GET /driver_instances/{driver_instance_id}/ping][%d] pingDriverInstanceInternalServerError  %+v", 500, o.Payload)
}

func (o *PingDriverInstanceInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
