package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PingInstanceReader is a Reader for the PingInstance structure.
type PingInstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PingInstanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPingInstanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewPingInstanceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPingInstanceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPingInstanceOK creates a PingInstanceOK with default headers values
func NewPingInstanceOK() *PingInstanceOK {
	return &PingInstanceOK{}
}

/*PingInstanceOK handles this case with default header values.

OK
*/
type PingInstanceOK struct {
}

func (o *PingInstanceOK) Error() string {
	return fmt.Sprintf("[GET /instances/{instance_id}/ping][%d] pingInstanceOK ", 200)
}

func (o *PingInstanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPingInstanceNotFound creates a PingInstanceNotFound with default headers values
func NewPingInstanceNotFound() *PingInstanceNotFound {
	return &PingInstanceNotFound{}
}

/*PingInstanceNotFound handles this case with default header values.

Not Found
*/
type PingInstanceNotFound struct {
}

func (o *PingInstanceNotFound) Error() string {
	return fmt.Sprintf("[GET /instances/{instance_id}/ping][%d] pingInstanceNotFound ", 404)
}

func (o *PingInstanceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPingInstanceInternalServerError creates a PingInstanceInternalServerError with default headers values
func NewPingInstanceInternalServerError() *PingInstanceInternalServerError {
	return &PingInstanceInternalServerError{}
}

/*PingInstanceInternalServerError handles this case with default header values.

Unexpected error
*/
type PingInstanceInternalServerError struct {
	Payload string
}

func (o *PingInstanceInternalServerError) Error() string {
	return fmt.Sprintf("[GET /instances/{instance_id}/ping][%d] pingInstanceInternalServerError  %+v", 500, o.Payload)
}

func (o *PingInstanceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
