package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPingInstanceParams creates a new PingInstanceParams object
// with the default values initialized.
func NewPingInstanceParams() *PingInstanceParams {
	var ()
	return &PingInstanceParams{}
}

/*PingInstanceParams contains all the parameters to send to the API endpoint
for the ping instance operation typically these are written to a http.Request
*/
type PingInstanceParams struct {

	/*InstanceID
	  Instance ID

	*/
	InstanceID string
}

// WithInstanceID adds the instanceId to the ping instance params
func (o *PingInstanceParams) WithInstanceID(InstanceID string) *PingInstanceParams {
	o.InstanceID = InstanceID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PingInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param instance_id
	if err := r.SetPathParam("instance_id", o.InstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
