package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPingDriverEndpointParams creates a new PingDriverEndpointParams object
// with the default values initialized.
func NewPingDriverEndpointParams() *PingDriverEndpointParams {
	var ()
	return &PingDriverEndpointParams{}
}

/*PingDriverEndpointParams contains all the parameters to send to the API endpoint
for the ping driver endpoint operation typically these are written to a http.Request
*/
type PingDriverEndpointParams struct {

	/*DriverEndpointID
	  Driver Endpoint ID

	*/
	DriverEndpointID string
}

// WithDriverEndpointID adds the driverEndpointId to the ping driver endpoint params
func (o *PingDriverEndpointParams) WithDriverEndpointID(DriverEndpointID string) *PingDriverEndpointParams {
	o.DriverEndpointID = DriverEndpointID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PingDriverEndpointParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param driver_endpoint_id
	if err := r.SetPathParam("driver_endpoint_id", o.DriverEndpointID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
