package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/SUSE/cf-usb-plugin/lib/models"
)

// NewRegisterDriverEndpointParams creates a new RegisterDriverEndpointParams object
// with the default values initialized.
func NewRegisterDriverEndpointParams() *RegisterDriverEndpointParams {
	var ()
	return &RegisterDriverEndpointParams{}
}

/*RegisterDriverEndpointParams contains all the parameters to send to the API endpoint
for the register driver endpoint operation typically these are written to a http.Request
*/
type RegisterDriverEndpointParams struct {

	/*DriverEndpoint
	  An endpoint to be registered with the USB

	*/
	DriverEndpoint *models.DriverEndpoint
}

// WithDriverEndpoint adds the driverEndpoint to the register driver endpoint params
func (o *RegisterDriverEndpointParams) WithDriverEndpoint(DriverEndpoint *models.DriverEndpoint) *RegisterDriverEndpointParams {
	o.DriverEndpoint = DriverEndpoint
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *RegisterDriverEndpointParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	if o.DriverEndpoint == nil {
		o.DriverEndpoint = new(models.DriverEndpoint)
	}

	if err := r.SetBodyParam(o.DriverEndpoint); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
