package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UnregisterDriverInstanceReader is a Reader for the UnregisterDriverInstance structure.
type UnregisterDriverInstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *UnregisterDriverInstanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewUnregisterDriverInstanceNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewUnregisterDriverInstanceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewUnregisterDriverInstanceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUnregisterDriverInstanceNoContent creates a UnregisterDriverInstanceNoContent with default headers values
func NewUnregisterDriverInstanceNoContent() *UnregisterDriverInstanceNoContent {
	return &UnregisterDriverInstanceNoContent{}
}

/*UnregisterDriverInstanceNoContent handles this case with default header values.

Driver endpoint unregistered
*/
type UnregisterDriverInstanceNoContent struct {
}

func (o *UnregisterDriverInstanceNoContent) Error() string {
	return fmt.Sprintf("[DELETE /driver_endpoints/{driver_endpoint_id}][%d] unregisterDriverInstanceNoContent ", 204)
}

func (o *UnregisterDriverInstanceNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUnregisterDriverInstanceNotFound creates a UnregisterDriverInstanceNotFound with default headers values
func NewUnregisterDriverInstanceNotFound() *UnregisterDriverInstanceNotFound {
	return &UnregisterDriverInstanceNotFound{}
}

/*UnregisterDriverInstanceNotFound handles this case with default header values.

Not Found
*/
type UnregisterDriverInstanceNotFound struct {
}

func (o *UnregisterDriverInstanceNotFound) Error() string {
	return fmt.Sprintf("[DELETE /driver_endpoints/{driver_endpoint_id}][%d] unregisterDriverInstanceNotFound ", 404)
}

func (o *UnregisterDriverInstanceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUnregisterDriverInstanceInternalServerError creates a UnregisterDriverInstanceInternalServerError with default headers values
func NewUnregisterDriverInstanceInternalServerError() *UnregisterDriverInstanceInternalServerError {
	return &UnregisterDriverInstanceInternalServerError{}
}

/*UnregisterDriverInstanceInternalServerError handles this case with default header values.

Unexpected error
*/
type UnregisterDriverInstanceInternalServerError struct {
	Payload string
}

func (o *UnregisterDriverInstanceInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /driver_endpoints/{driver_endpoint_id}][%d] unregisterDriverInstanceInternalServerError  %+v", 500, o.Payload)
}

func (o *UnregisterDriverInstanceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
