package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUnregisterDriverInstanceParams creates a new UnregisterDriverInstanceParams object
// with the default values initialized.
func NewUnregisterDriverInstanceParams() *UnregisterDriverInstanceParams {
	var ()
	return &UnregisterDriverInstanceParams{}
}

/*UnregisterDriverInstanceParams contains all the parameters to send to the API endpoint
for the unregister driver instance operation typically these are written to a http.Request
*/
type UnregisterDriverInstanceParams struct {

	/*DriverEndpointID
	  Driver Endpoint ID

	*/
	DriverEndpointID string
}

// WithDriverEndpointID adds the driverEndpointId to the unregister driver instance params
func (o *UnregisterDriverInstanceParams) WithDriverEndpointID(DriverEndpointID string) *UnregisterDriverInstanceParams {
	o.DriverEndpointID = DriverEndpointID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UnregisterDriverInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param driver_endpoint_id
	if err := r.SetPathParam("driver_endpoint_id", o.DriverEndpointID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
