package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hpcloud/cf-plugin-usb/lib/models"
)

// NewUpdateServicePlanParams creates a new UpdateServicePlanParams object
// with the default values initialized.
func NewUpdateServicePlanParams() *UpdateServicePlanParams {
	var ()
	return &UpdateServicePlanParams{}
}

/*UpdateServicePlanParams contains all the parameters to send to the API endpoint
for the update service plan operation typically these are written to a http.Request
*/
type UpdateServicePlanParams struct {

	/*Plan
	  Update plan

	*/
	Plan *models.Plan
	/*PlanID
	  ID of the plan

	*/
	PlanID string
}

// WithPlan adds the plan to the update service plan params
func (o *UpdateServicePlanParams) WithPlan(Plan *models.Plan) *UpdateServicePlanParams {
	o.Plan = Plan
	return o
}

// WithPlanID adds the planId to the update service plan params
func (o *UpdateServicePlanParams) WithPlanID(PlanID string) *UpdateServicePlanParams {
	o.PlanID = PlanID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateServicePlanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	if o.Plan == nil {
		o.Plan = new(models.Plan)
	}

	if err := r.SetBodyParam(o.Plan); err != nil {
		return err
	}

	// path param plan_id
	if err := r.SetPathParam("plan_id", o.PlanID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
