package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/hpcloud/cf-plugin-usb/lib/models"
)

// UpdateDialReader is a Reader for the UpdateDial structure.
type UpdateDialReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *UpdateDialReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateDialOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewUpdateDialNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewUpdateDialInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateDialOK creates a UpdateDialOK with default headers values
func NewUpdateDialOK() *UpdateDialOK {
	return &UpdateDialOK{}
}

/*UpdateDialOK handles this case with default header values.

Sucessfull response
*/
type UpdateDialOK struct {
	Payload *models.Dial
}

func (o *UpdateDialOK) Error() string {
	return fmt.Sprintf("[PUT /dials/{dial_id}][%d] updateDialOK  %+v", 200, o.Payload)
}

func (o *UpdateDialOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Dial)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateDialNotFound creates a UpdateDialNotFound with default headers values
func NewUpdateDialNotFound() *UpdateDialNotFound {
	return &UpdateDialNotFound{}
}

/*UpdateDialNotFound handles this case with default header values.

Not Found
*/
type UpdateDialNotFound struct {
}

func (o *UpdateDialNotFound) Error() string {
	return fmt.Sprintf("[PUT /dials/{dial_id}][%d] updateDialNotFound ", 404)
}

func (o *UpdateDialNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateDialInternalServerError creates a UpdateDialInternalServerError with default headers values
func NewUpdateDialInternalServerError() *UpdateDialInternalServerError {
	return &UpdateDialInternalServerError{}
}

/*UpdateDialInternalServerError handles this case with default header values.

Unexpected error
*/
type UpdateDialInternalServerError struct {
	Payload string
}

func (o *UpdateDialInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /dials/{dial_id}][%d] updateDialInternalServerError  %+v", 500, o.Payload)
}

func (o *UpdateDialInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
