package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hpcloud/cf-plugin-usb/lib/models"
)

// NewUpdateDialParams creates a new UpdateDialParams object
// with the default values initialized.
func NewUpdateDialParams() *UpdateDialParams {
	var ()
	return &UpdateDialParams{}
}

/*UpdateDialParams contains all the parameters to send to the API endpoint
for the update dial operation typically these are written to a http.Request
*/
type UpdateDialParams struct {

	/*Dial
	  Updated dial

	*/
	Dial *models.Dial
	/*DialID
	  ID of the dial

	*/
	DialID string
}

// WithDial adds the dial to the update dial params
func (o *UpdateDialParams) WithDial(Dial *models.Dial) *UpdateDialParams {
	o.Dial = Dial
	return o
}

// WithDialID adds the dialId to the update dial params
func (o *UpdateDialParams) WithDialID(DialID string) *UpdateDialParams {
	o.DialID = DialID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateDialParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	if o.Dial == nil {
		o.Dial = new(models.Dial)
	}

	if err := r.SetBodyParam(o.Dial); err != nil {
		return err
	}

	// path param dial_id
	if err := r.SetPathParam("dial_id", o.DialID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
