package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hpcloud/cf-plugin-usb/lib/models"
)

// NewUpdateDriverParams creates a new UpdateDriverParams object
// with the default values initialized.
func NewUpdateDriverParams() *UpdateDriverParams {
	var ()
	return &UpdateDriverParams{}
}

/*UpdateDriverParams contains all the parameters to send to the API endpoint
for the update driver operation typically these are written to a http.Request
*/
type UpdateDriverParams struct {

	/*Driver
	  Driver to be updated

	*/
	Driver *models.Driver
	/*DriverID
	  Driver ID

	*/
	DriverID string
}

// WithDriver adds the driver to the update driver params
func (o *UpdateDriverParams) WithDriver(Driver *models.Driver) *UpdateDriverParams {
	o.Driver = Driver
	return o
}

// WithDriverID adds the driverId to the update driver params
func (o *UpdateDriverParams) WithDriverID(DriverID string) *UpdateDriverParams {
	o.DriverID = DriverID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateDriverParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	if o.Driver == nil {
		o.Driver = new(models.Driver)
	}

	if err := r.SetBodyParam(o.Driver); err != nil {
		return err
	}

	// path param driver_id
	if err := r.SetPathParam("driver_id", o.DriverID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
