package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UploadDriverReader is a Reader for the UploadDriver structure.
type UploadDriverReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *UploadDriverReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUploadDriverOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewUploadDriverNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewUploadDriverInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUploadDriverOK creates a UploadDriverOK with default headers values
func NewUploadDriverOK() *UploadDriverOK {
	return &UploadDriverOK{}
}

/*UploadDriverOK handles this case with default header values.

Driver uploaded
*/
type UploadDriverOK struct {
}

func (o *UploadDriverOK) Error() string {
	return fmt.Sprintf("[PUT /drivers/{driver_id}/bits][%d] uploadDriverOK ", 200)
}

func (o *UploadDriverOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUploadDriverNotFound creates a UploadDriverNotFound with default headers values
func NewUploadDriverNotFound() *UploadDriverNotFound {
	return &UploadDriverNotFound{}
}

/*UploadDriverNotFound handles this case with default header values.

Not Found
*/
type UploadDriverNotFound struct {
}

func (o *UploadDriverNotFound) Error() string {
	return fmt.Sprintf("[PUT /drivers/{driver_id}/bits][%d] uploadDriverNotFound ", 404)
}

func (o *UploadDriverNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUploadDriverInternalServerError creates a UploadDriverInternalServerError with default headers values
func NewUploadDriverInternalServerError() *UploadDriverInternalServerError {
	return &UploadDriverInternalServerError{}
}

/*UploadDriverInternalServerError handles this case with default header values.

Unexpected error
*/
type UploadDriverInternalServerError struct {
	Payload string
}

func (o *UploadDriverInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /drivers/{driver_id}/bits][%d] uploadDriverInternalServerError  %+v", 500, o.Payload)
}

func (o *UploadDriverInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
